### ISSUE TITLE
 var React = require('react') instead of  var React = require('React');

### ISSUE THREAD

**Issue by samidarko** [tylermcginnis/react-flux-gulp-browserify-reactrouter-firebase-starterkit#2]
In:
[App.js](https://github.com/tylermcginnis/react-flux-gulp-browserify-reactrouter-firebase-starterkit/blob/master/src/js/components/App.js) 
And: 
[Route.js](https://github.com/tylermcginnis/react-flux-gulp-browserify-reactrouter-firebase-starterkit/blob/master/src/js/config/Routes.js)

**Comment by tylermcginnis** [comment]
I don't think that's right. https://www.npmjs.com/package/react

**Comment by samidarko** [comment]
Sorry @tylermcginnis, I made a mistake in the title of the issue, so I fixed it :)
Btw, thanks for the very good articles on your [blog](http://tylermcginnis.com/blog/) and tutorial on [egghead](https://egghead.io/)
